// Betterbird preferences -- managed by chezmoi
//   source: home/private_dot_thunderbird/p4dv0owj.default-default/prefs.js
//
// Curated by hand: account definitions, identities, servers, SMTP, CardDAV
// and calendars, plus chosen preferences. Volatile state (update timestamps,
// build/schema versions, telemetry ids, absolute paths, EWS sync tokens) is
// stripped so this file stays diff-stable.
//
// NO CREDENTIALS HERE. Passwords and OAuth tokens live in the profile's
// key4.db + logins.json, which chezmoi does not track. On a new machine the
// accounts below are recreated and you sign in once per account.
//
// Betterbird rewrites prefs.js itself when it exits. To change a setting:
// change it in the app, then `chezmoi diff ~/.thunderbird` and fold the wanted
// lines into this file. Do not edit the live file by hand.
user_pref("betterbird.update.blocklist", "{\"140\":{\"TagToolbar\":{\"id\":\"{61A64500-335C-418D-8FCB-E072A9ABF3DA}\",\"version\":\"*\"},\"CardBook\":{\"id\":\"cardbook@vigneau.philippe\",\"version\":\"100.2\"},\"ManuallySortFolders\":{\"id\":\"tbsortfolders@xulforum.org\",\"version\":\"*\"},\"ConfirmAddress\":{\"id\":\"confirm-address@kenmaz.net\",\"version\":\"*\"}},\"153\":{\"TagToolbar\":{\"id\":\"{61A64500-335C-418D-8FCB-E072A9ABF3DA}\",\"version\":\"*\"},\"CardBook\":{\"id\":\"cardbook@vigneau.philippe\",\"version\":\"100.2\"},\"ManuallySortFolders\":{\"id\":\"tbsortfolders@xulforum.org\",\"version\":\"*\"},\"ConfirmAddress\":{\"id\":\"confirm-address@kenmaz.net\",\"version\":\"*\"},\"CloseToTray\":{\"id\":\"@close-to-tray.lachcim\",\"version\":\"*\"}}}");
user_pref("browser.search.region", "DK");
user_pref("browser.theme.content-theme", 0);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("calendar.list.sortOrder", "39d090d5-3cec-42e3-a216-4af9f9a04c09 5bf73477-c303-464d-8351-60bbbc01b16f");
user_pref("calendar.registry.39d090d5-3cec-42e3-a216-4af9f9a04c09.cache.enabled", true);
user_pref("calendar.registry.39d090d5-3cec-42e3-a216-4af9f9a04c09.calendar-main-default", true);
user_pref("calendar.registry.39d090d5-3cec-42e3-a216-4af9f9a04c09.calendar-main-in-composite", true);
user_pref("calendar.registry.39d090d5-3cec-42e3-a216-4af9f9a04c09.color", "#33d17a");
user_pref("calendar.registry.39d090d5-3cec-42e3-a216-4af9f9a04c09.disabled", false);
user_pref("calendar.registry.39d090d5-3cec-42e3-a216-4af9f9a04c09.imip.identity.key", "id1");
user_pref("calendar.registry.39d090d5-3cec-42e3-a216-4af9f9a04c09.name", "Kalender");
user_pref("calendar.registry.39d090d5-3cec-42e3-a216-4af9f9a04c09.notifications.times", "");
user_pref("calendar.registry.39d090d5-3cec-42e3-a216-4af9f9a04c09.readOnly", false);
user_pref("calendar.registry.39d090d5-3cec-42e3-a216-4af9f9a04c09.refreshInterval", "30");
user_pref("calendar.registry.39d090d5-3cec-42e3-a216-4af9f9a04c09.suppressAlarms", false);
user_pref("calendar.registry.39d090d5-3cec-42e3-a216-4af9f9a04c09.type", "caldav");
user_pref("calendar.registry.39d090d5-3cec-42e3-a216-4af9f9a04c09.uri", "https://mail.kappelpersson.dk:2080/calendars/mikkel@kappelpersson.dk/calendar/");
user_pref("calendar.registry.39d090d5-3cec-42e3-a216-4af9f9a04c09.username", "mikkel@kappelpersson.dk");
user_pref("calendar.registry.5bf73477-c303-464d-8351-60bbbc01b16f.cache.enabled", true);
user_pref("calendar.registry.5bf73477-c303-464d-8351-60bbbc01b16f.calendar-main-in-composite", true);
user_pref("calendar.registry.5bf73477-c303-464d-8351-60bbbc01b16f.color", "#f6d32d");
user_pref("calendar.registry.5bf73477-c303-464d-8351-60bbbc01b16f.name", "Familiekalender");
user_pref("calendar.registry.5bf73477-c303-464d-8351-60bbbc01b16f.readOnly", false);
user_pref("calendar.registry.5bf73477-c303-464d-8351-60bbbc01b16f.type", "caldav");
user_pref("calendar.registry.5bf73477-c303-464d-8351-60bbbc01b16f.uri", "https://mail.kappelpersson.dk:2080/calendars/mikkel@kappelpersson.dk/calendar-c50d3ae7-62ce-4794-bc8e-c6c73f674c03/");
user_pref("calendar.registry.5bf73477-c303-464d-8351-60bbbc01b16f.username", "mikkel@kappelpersson.dk");
user_pref("calendar.timezone.local", "Europe/Copenhagen");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("doh-rollout.home-region", "DK");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.webextensions.uuids", "{\"tbpro-system-add-on@thunderbird.net\":\"34444d5b-223c-4048-b8a2-e41c56dc76dc\",\"default-theme@mozilla.org\":\"b9b90642-1a03-4f6b-ad15-fd8f8904dde7\",\"gconversation@xulforum.org\":\"5b5bc91a-5f54-4a62-a6e8-f617f4d6a5c9\"}");
user_pref("intl.regional_prefs.use_os_locales", true);
user_pref("layout.css.always_underline_links", true);
user_pref("ldap_2.servers.cPanelCardDavkontakter.carddav.syncinterval", 30);
user_pref("ldap_2.servers.cPanelCardDavkontakter.carddav.url", "https://mail.kappelpersson.dk:2080/addressbooks/mikkel@kappelpersson.dk/addressbook/");
user_pref("ldap_2.servers.cPanelCardDavkontakter.carddav.username", "mikkel@kappelpersson.dk");
user_pref("ldap_2.servers.cPanelCardDavkontakter.description", "cPanel CardDav kontakter");
user_pref("ldap_2.servers.cPanelCardDavkontakter.dirType", 102);
user_pref("ldap_2.servers.cPanelCardDavkontakter.filename", "abook-2.sqlite");
user_pref("ldap_2.servers.cPanelCardDavkontakter.uid", "1c16d31a-d2b7-473a-bc38-deb4cd2e7d55");
user_pref("mail.account.account1.identities", "id1");
user_pref("mail.account.account1.server", "server2");
user_pref("mail.account.account2.server", "server3");
user_pref("mail.account.account3.identities", "id2");
user_pref("mail.account.account3.server", "server4");
user_pref("mail.account.account4.identities", "id3");
user_pref("mail.account.account4.server", "server6");
user_pref("mail.account.lastKey", 4);
user_pref("mail.accountmanager.accounts", "account1,account3,account4,account2");
user_pref("mail.accountmanager.defaultaccount", "account1");
user_pref("mail.accountmanager.localfoldersserver", "server3");
user_pref("mail.ews.server_versions", "{\"https://outlook.office365.com/ews/exchange.asmx\":\"Exchange2013_SP1\"}");
user_pref("mail.exchange.hasMicrosoft365EwsAccount", true);
user_pref("mail.identity.id1.archive_folder", "imap://mikkel%40kappelpersson.dk@mail.kappelpersson.dk/INBOX/Archive");
user_pref("mail.identity.id1.archives_folder_picker_mode", "1");
user_pref("mail.identity.id1.doBcc", false);
user_pref("mail.identity.id1.draft_folder", "imap://mikkel%40kappelpersson.dk@mail.kappelpersson.dk/INBOX/Drafts");
user_pref("mail.identity.id1.drafts_folder_picker_mode", "1");
user_pref("mail.identity.id1.fcc_folder", "imap://mikkel%40kappelpersson.dk@mail.kappelpersson.dk/INBOX/Sent");
user_pref("mail.identity.id1.fcc_folder_picker_mode", "1");
user_pref("mail.identity.id1.fullName", "Mikkel Kappel Persson");
user_pref("mail.identity.id1.reply_on_top", 1);
user_pref("mail.identity.id1.sig_bottom", false);
user_pref("mail.identity.id1.smtpServer", "smtp1");
user_pref("mail.identity.id1.stationery_folder", "imap://mikkel%40kappelpersson.dk@mail.kappelpersson.dk/Templates");
user_pref("mail.identity.id1.tmpl_folder_picker_mode", "0");
user_pref("mail.identity.id1.useremail", "mikkel@kappelpersson.dk");
user_pref("mail.identity.id1.valid", true);
user_pref("mail.identity.id2.draft_folder", "imap://mikkelkp%40hotmail.com@outlook.office365.com/Drafts");
user_pref("mail.identity.id2.drafts_folder_picker_mode", "0");
user_pref("mail.identity.id2.fcc_folder", "imap://mikkelkp%40hotmail.com@outlook.office365.com/Sent");
user_pref("mail.identity.id2.fcc_folder_picker_mode", "0");
user_pref("mail.identity.id2.fullName", "Mikkel Kappel Persson");
user_pref("mail.identity.id2.reply_on_top", 1);
user_pref("mail.identity.id2.sig_bottom", false);
user_pref("mail.identity.id2.smtpServer", "smtp2");
user_pref("mail.identity.id2.stationery_folder", "imap://mikkelkp%40hotmail.com@outlook.office365.com/Templates");
user_pref("mail.identity.id2.tmpl_folder_picker_mode", "0");
user_pref("mail.identity.id2.useremail", "mikkelkp@hotmail.com");
user_pref("mail.identity.id2.valid", true);
user_pref("mail.identity.id3.doBcc", false);
user_pref("mail.identity.id3.draft_folder", "ews://fs62fb%40student.aau.dk@outlook.office365.com/Drafts");
user_pref("mail.identity.id3.drafts_folder_picker_mode", "1");
user_pref("mail.identity.id3.fcc_folder", "ews://fs62fb%40student.aau.dk@outlook.office365.com/Sent%20Items");
user_pref("mail.identity.id3.fcc_folder_picker_mode", "1");
user_pref("mail.identity.id3.fullName", "Mikkel Kappel Persson");
user_pref("mail.identity.id3.reply_on_top", 1);
user_pref("mail.identity.id3.sig_bottom", false);
user_pref("mail.identity.id3.smtpServer", "ews1");
user_pref("mail.identity.id3.useremail", "fs62fb@student.aau.dk");
user_pref("mail.identity.id3.valid", true);
user_pref("mail.inline_attachments", false);
user_pref("mail.last_msg_movecopy_target_uri", "imap://mikkel%40kappelpersson.dk@mail.kappelpersson.dk/INBOX");
user_pref("mail.outgoingserver.ews1.auth_method", 10);
user_pref("mail.outgoingserver.ews1.description", "Microsoft 365");
user_pref("mail.outgoingserver.ews1.ews_url", "https://outlook.office365.com/ews/exchange.asmx");
user_pref("mail.outgoingserver.ews1.key", "ews1");
user_pref("mail.outgoingserver.ews1.username", "fs62fb@student.aau.dk");
user_pref("mail.pane_config.dynamic", 2);
user_pref("mail.root.ews-rel", "[ProfD]Mail");
user_pref("mail.root.imap-rel", "[ProfD]ImapMail");
user_pref("mail.root.none-rel", "[ProfD]Mail");
user_pref("mail.server.server2.check_new_mail", true);
user_pref("mail.server.server2.clientid", "08dcde08-1d5c-4a98-af68-069998e1c148");
user_pref("mail.server.server2.color", "#8ff0a4");
user_pref("mail.server.server2.directory-rel", "[ProfD]ImapMail/mail.kappelpersson.dk");
user_pref("mail.server.server2.hostname", "mail.kappelpersson.dk");
user_pref("mail.server.server2.login_at_startup", true);
user_pref("mail.server.server2.max_cached_connections", 5);
user_pref("mail.server.server2.moveOnSpam", true);
user_pref("mail.server.server2.name", "mikkel@kappelpersson.dk");
user_pref("mail.server.server2.namespace.personal", "\"INBOX.\"");
user_pref("mail.server.server2.port", 993);
user_pref("mail.server.server2.purgeSpam", true);
user_pref("mail.server.server2.purgeSpamInterval", 30);
user_pref("mail.server.server2.socketType", 3);
user_pref("mail.server.server2.spamActionTargetAccount", "imap://mikkel%40kappelpersson.dk@mail.kappelpersson.dk");
user_pref("mail.server.server2.spamActionTargetFolder", "imap://mikkel%40kappelpersson.dk@mail.kappelpersson.dk/Junk");
user_pref("mail.server.server2.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.server.server2.timeout", 29);
user_pref("mail.server.server2.trash_folder_name", "INBOX/Trash");
user_pref("mail.server.server2.type", "imap");
user_pref("mail.server.server2.userName", "mikkel@kappelpersson.dk");
user_pref("mail.server.server2.whiteListAbURI", "jscarddav://abook-2.sqlite jsaddrbook://abook.sqlite");
user_pref("mail.server.server3.directory-rel", "[ProfD]Mail/Local Folders");
user_pref("mail.server.server3.hostname", "Local Folders");
user_pref("mail.server.server3.name", "Local Folders");
user_pref("mail.server.server3.spamActionTargetAccount", "mailbox://nobody@Local%20Folders");
user_pref("mail.server.server3.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.server.server3.type", "none");
user_pref("mail.server.server3.userName", "nobody");
user_pref("mail.server.server4.authMethod", 10);
user_pref("mail.server.server4.check_new_mail", true);
user_pref("mail.server.server4.clientid", "05d72266-5db6-47fa-86f7-759e1aec1e14");
user_pref("mail.server.server4.color", "#99c1f1");
user_pref("mail.server.server4.directory-rel", "[ProfD]ImapMail/outlook.office365.com");
user_pref("mail.server.server4.hostname", "outlook.office365.com");
user_pref("mail.server.server4.login_at_startup", true);
user_pref("mail.server.server4.max_cached_connections", 5);
user_pref("mail.server.server4.moveOnSpam", true);
user_pref("mail.server.server4.name", "mikkelkp@hotmail.com");
user_pref("mail.server.server4.namespace.personal", "\"\"");
user_pref("mail.server.server4.port", 993);
user_pref("mail.server.server4.purgeSpam", true);
user_pref("mail.server.server4.purgeSpamInterval", 30);
user_pref("mail.server.server4.socketType", 3);
user_pref("mail.server.server4.spamActionTargetAccount", "imap://mikkelkp%40hotmail.com@outlook.office365.com");
user_pref("mail.server.server4.spamActionTargetFolder", "imap://mikkelkp%40hotmail.com@outlook.office365.com/Junk");
user_pref("mail.server.server4.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.server.server4.timeout", 29);
user_pref("mail.server.server4.trash_folder_name", "Deleted");
user_pref("mail.server.server4.type", "imap");
user_pref("mail.server.server4.userName", "mikkelkp@hotmail.com");
user_pref("mail.server.server4.whiteListAbURI", "jscarddav://abook-2.sqlite jsaddrbook://abook.sqlite");
user_pref("mail.server.server6.authMethod", 10);
user_pref("mail.server.server6.check_new_mail", true);
user_pref("mail.server.server6.clientid", "cd794cb2-22d7-424a-94af-3eaff380754b");
user_pref("mail.server.server6.color", "#dc8add");
user_pref("mail.server.server6.directory-rel", "[ProfD]Mail/outlook.office365.com");
user_pref("mail.server.server6.ews_url", "https://outlook.office365.com/ews/exchange.asmx");
user_pref("mail.server.server6.hostname", "outlook.office365.com");
user_pref("mail.server.server6.login_at_startup", true);
user_pref("mail.server.server6.moveOnSpam", true);
user_pref("mail.server.server6.moveTargetMode", 1);
user_pref("mail.server.server6.name", "fs62fb@student.aau.dk");
user_pref("mail.server.server6.port", 0);
user_pref("mail.server.server6.purgeSpam", true);
user_pref("mail.server.server6.purgeSpamInterval", 30);
user_pref("mail.server.server6.socketType", 3);
user_pref("mail.server.server6.spamActionTargetAccount", "ews://fs62fb%40student.aau.dk@outlook.office365.com");
user_pref("mail.server.server6.spamActionTargetFolder", "ews://fs62fb%40student.aau.dk@outlook.office365.com/Junk%20Email");
user_pref("mail.server.server6.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.server.server6.trash_folder_path", "Deleted Items");
user_pref("mail.server.server6.type", "ews");
user_pref("mail.server.server6.userName", "fs62fb@student.aau.dk");
user_pref("mail.smtp.defaultserver", "smtp1");
user_pref("mail.smtpserver.ews1.type", "ews");
user_pref("mail.smtpserver.smtp1.authMethod", 3);
user_pref("mail.smtpserver.smtp1.description", "");
user_pref("mail.smtpserver.smtp1.hostname", "mail.kappelpersson.dk");
user_pref("mail.smtpserver.smtp1.port", 465);
user_pref("mail.smtpserver.smtp1.try_ssl", 3);
user_pref("mail.smtpserver.smtp1.type", "smtp");
user_pref("mail.smtpserver.smtp1.username", "mikkel@kappelpersson.dk");
user_pref("mail.smtpserver.smtp2.authMethod", 10);
user_pref("mail.smtpserver.smtp2.description", "Outlook.com (Microsoft)");
user_pref("mail.smtpserver.smtp2.hostname", "smtp-mail.outlook.com");
user_pref("mail.smtpserver.smtp2.port", 587);
user_pref("mail.smtpserver.smtp2.try_ssl", 2);
user_pref("mail.smtpserver.smtp2.type", "smtp");
user_pref("mail.smtpserver.smtp2.username", "mikkelkp@hotmail.com");
user_pref("mail.smtpservers", "smtp1,smtp2,ews1");
user_pref("mail.threadpane.listview", 0);
user_pref("mailnews.default_sort_order", 1);
user_pref("mailnews.default_view_flags", 1);
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.scroll_to_new_message", false);
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("telemetry.fog.init_on_shutdown", false);
